### ISSUE TITLE
fix: Error en commit c12a08b7a652fe1b98dc12f40e2ba7c633cf26ea

### ISSUE THREAD

**Issue by dantorval-us** [pabramber/decide-part-chiclana#109]
El commit con código "c12a08b7a652fe1b98dc12f40e2ba7c633cf26ea" se ha realizado directamente a la rama master, en lugar de a decide-part-chiclana-1.
Además, hay varios errores en los siguientes tests:
- test_filter
- test_hasvote
- test_vote
- test_voting_status
- test_complete_voting

**Comment by albertobemo7** [comment]
Se ha revertido el commit y se han identificado los fallos para el futuro commit a la rama correcta. Los fallos vienen dado por la ausencia del fichero html con la plantilla para email.
