### ISSUE TITLE
change: Traducir correctamente el atributo 'tipo' del modelo de 'Question'

### ISSUE THREAD

**Issue by juangarcia16** [pabramber/decide-part-chiclana#110]
Se propone como propuesta de mejora, enfocada en la culminación del proyecto, la traducción del atributo **tipo** correspondiente al modelo de **Question** para preservar una mayor coherencia con el resto del código, que se encuentra escrito en inglés.

Esto implica la revisión del modelo, vistas, tests... en los que dicho atributo sea utilizado para mantener el correcto funcionamiento de la aplicación.

**Comment by dantorval-us** [comment]
Solved
