### ISSUE TITLE
change: Borrar el atributo tipo del modelo Voting

### ISSUE THREAD

**Issue by juangarcia16** [pabramber/decide-part-chiclana#117]
Inicialmente se creó este atributo para la integración de los distintos tipos de votación pero a la hora de la implementación se prefirió establecer un atributo tipo en **Question** pues era más acorde a lo que se quería desarrollar.

Se pide eliminar este atributo puesto que el uso de este es meramente informativo y carece de funcionalidad

**Comment by dantorval-us** [comment]
Solved
