### ISSUE TITLE
change: Crear los tests para la funcionalidad de votación por puntuación

### ISSUE THREAD

**Issue by juangarcia16** [pabramber/decide-part-chiclana#120]
Ante la abrupta salida del grupo del desarrollador encargado de este incremento, la funcionalidad se ha quedado olvidada. Por lo que ha de ser actualizada y, por supuesto, testeada.

En una incidencia anterior ya se gestionó la actualización e integración de la funcionalidad. Sin embargo, es necesario la realización de los tests pertinentenes a este nuevo tipo de votación.

**Comment by dantorval-us** [comment]
Solved
