### ISSUE TITLE
fix: Test Selenium para guardar votación

### ISSUE THREAD

**Issue by dantorval-us** [pabramber/decide-part-chiclana#132]
El test de TestSaveVotingFile (en decide/voting/test_selenium.py) funciona correctamente en local, con la dirección "http://localhost:8000/admin/login/?next=/admin/" y un usuario ya existe en la base de datos, creado con el comando: psql -c "create user <usuario> with password '<contraseña>'", pero cuando se accede con la dirección "f'{self.live_server_url}/admin/" muestra un **error 500** al realizar el tally.
Dejo el test comentado, de manera que se pueda probar en local.

**Comment by juangarcia16** [comment]
**Actualización**
Se ha intentado resolver el error probando con la creación de superusuarios a través del modelo de User.
Se ha intentado resolver el error probando con el método setUp de la clase de BaseTestCase().
Se ha intentado resolver el error probando a cambiar la dirección proporcionada en el Auth por la dirección en la que es desplegado el test.

Ninguna de estas pruebas ha resuelto el error. Se procede a cancelar esta issue ante la no resolución del error.
