### ISSUE TITLE
fix: Votación con usuario anteriormente deslogueado

### ISSUE THREAD

**Issue by raulgr23** [pabramber/decide-part-chiclana#155]
Cuando haces una votación estando logueado y te sales y haces logout, al volver a entrar por url puedes votar con el usuario anterior. 

Los pasos para reproducir el fallo son:

1. Haces login en la página principal
2. Te diriges a una votación en la que estés en el censo
3. Votas
4. Vuelves a la página principal y haces logout
5. Vuelves a la votación de antes con la url de antes
6. Puedes votar con el usuario con el que estabas logueado antes

**Comment by borpincal** [comment]
Acabo de subir un commit areglando lo que comentas. Cierro la issue.
