### ISSUE TITLE
(fix): Error recuento borda

### ISSUE THREAD

**Issue by nurgomari** [pabramber/decide-part-chiclana#167]
Al hacer el recuento de una votación con el recuento borda da un error
Pasos para recrear el error:
1. Creas e inicias una votacion con postprocesado borda
2. Votas con un usario del censo
3. Detienes la votacion
4. Haces el recuento (tally)

**Comment by raulgr23** [comment]
He hecho un commit solucionando el error que comentas. Cerraré la issue.
