### ISSUE TITLE
fix: No se puede autenticar para votar

### ISSUE THREAD

**Issue by pabramber** [pabramber/decide-part-chiclana#84]
A la hora de votar, cuando te pide autenticarte, no puedes, y por tanto, no puedes votar. Los pasos a seguir para reproducir el error:
* Crear la votación con datos cualquiera pues en sí no es un fallo de votar si no a la hora de autenticar. Detallar el auth que es http://localhost:8000 con `Me` activado, que si puede afectar, aunque lo dudo pues siempre lo he indicado así.
* Añadir al censo el usuario con id 1 a la votación 1. En caso de la votación recién creada no tenga el id = 1 habría que cambiarlo.
* Empezar la votación anterior con `Start` y `Go`
* Ir a la url `localhost:8000\booth\1`
* Aquí ya surge el error: ![imagen](https://user-images.githubusercontent.com/99967600/205454197-b14dc66f-1f3c-4f1d-9201-9566203f07f0.png)

Ya que no es una excepción, no muestra información de debug, por lo que dejo por aquí los resultados de consola:

![imagen](https://user-images.githubusercontent.com/99967600/205454659-919fbd7b-703b-440c-ab19-5f5284f4287d.png)

**Comment by raulgr23** [comment]
Prueba a eliminar las tablas, ejecutando:

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;

**Comment by pabramber** [comment]
Pues sería algun conflicto con la base de datos entonces, pues ya me funciona. Cierro la issue.
