### ISSUE TITLE
fix: No se pueden ordenar las opciones en el tipo Preference

### ISSUE THREAD

**Issue by borpincal** [pabramber/decide-part-chiclana#92]
Cuando se va a seleccionar el orden de las opciones solo aparece para marcar una opción por lo que no se puede ordenar. Los pasos para reproducirlo son:

- Creación de una pregunta tipo `PREFERENCE` con la opción `Create ordination` seleccionada y se crean las opciones.
- Creamos una pregunta de tipo  `PREFERENCE VOTING` y seleccionamos la pregunta creada en el paso anterior
- Creamos un censo donde incluyamos el id de la votación anterior y el id de un usuario para poder votar
- Iniciamos la votación anterior seleccionándola y dando en el botón `Start`
- Nos dirigimos a la siguiente url `http://localhost:8000/booth/id-votacion` donde `id-votacion` es el id de la votación creada anteriormente

Nos aparece la siguiente pantalla:
![imagen](https://user-images.githubusercontent.com/99967105/205486581-a46f178c-b774-4a4b-bb88-3b212579d1ce.png)

Podemos comprobar que no se pueden ordenar las opciones que aparecen

**Comment by juangarcia16** [comment]
**Actualización**
El error que te ocurre es debido a que el procedimiento correcto para la creación de una pregunta por preferencia es:

- Creamos una pregunta de tipo 'Preference' y añadimos el resto de sus atributos (incluidas las opciones de la pregunta). Por último, nos aseguramos de que la casilla de 'Create ordination' está DESMARCADA.
- Procedemos a guardar la pregunta.
- Una vez guardada ahora sí procedemos a marcar la casilla 'Create ordination'. Y ahora debería de ordenar correctamente las opciones introducidas.

Esto se debe a que el algoritmo de ordenación de las preguntas requiere de que la pregunta y sus posibles opciones ya hayan sido introducidas y guardadas para su correcto funcionamiento

**Comment by borpincal** [comment]
Cierto lo estaba haciendo yo mal. Ya funciona. Cierro la issue.
